name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  add-linter-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: marian-code/python-lint-annotate@v3
  full-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: psf/black@stable
    