name: PR Checks
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
permissions:
  pull-requests: write
jobs:
  add-linter-annotations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: marian-code/python-lint-annotate@v3
        with:
            python-root-list: ".|grep -v conf.py"
  full-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run black
        uses: psf/black@stable
      - uses: chartboost/ruff-action@v1
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y coinor-cbc
      - name: Run unittests
        run: |
          coverage run --source=. -m unittest tests/*_test.py tests/*/*_test.py
      - name: Generate coverage.xml
        run: |
          coverage xml
      - name: Get Coverage 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: .95